export const errorCodes = {
  EMPTY_ERROR: 10,
  CITY_IS_NOT_SERVED: 26,
  NEGATIVE_NUMBER: 30,
  ACCOUNT_IS_NOT_ACTIVATED: 40,
  TOO_MANY_LOGIN_TRIES: 50,

  // INVALID TYPE
  INVALID_FIRST_NAME: 101,
  INVALID_LAST_NAME: 102,
  INVALID_EMAIL: 103,
  INVALID_EMAIL_LENGTH: 203,
  INVALID_TEL_NUM: 104,
  INVALID_TEL_NUM_LENGTH: 204,
  INVALID_PASSWORD: 105,
  INVALID_PASSWORD_LENGTH: 205,
  PASSWORDS_ARE_NOT_EQUAL: 106,
  INVALID_CITY_NAME: 107,
  INVALID_STREET_NAME: 108,
  INVALID_HOUSE_NUMBER: 109,
  INVALID_FLAT_NUMBER: 110,
  INVALID_SUBJECT: 111,

  // REGEX
  PASSWORD_NOT_ALL_REQUIRED_SYMBOLS_ERROR: 45,
  FIRST_NAME_NOT_ALLOWED_SYMBOLS_ERROR: 51,
  LAST_NAME_NOT_ALLOWED_SYMBOLS_ERROR: 52,
  EMAIL_NOT_ALLOWED_SYMBOLS_ERROR: 53,
  TEL_NUM_NOT_ALLOWED_SYMBOLS_ERROR: 54,
  PASSWORD_NOT_ALLOWED_SYMBOLS_ERROR: 55,

  // NOT EQUALS
  EMAIL_DOES_NOT_EXIST: 303,
  PASSWORD_DOES_NOT_EXIST: 305,

  OLD_EMAIL_DOES_NOT_MATCH: 403,
  OLD_TEL_NUM_DOES_NOT_MATCH: 404,
  OLD_PASSWORD_DOES_NOT_MATCH: 405,

  // LENGTH
  TEL_NUM_LENGTH: 13,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 30,
  EMAIL_LOCAL_OR_DOMAIN_PART_MIN_LENGTH: 1,
  EMAIL_LOCAL_PART_MAX_LENGTH: 63,
  EMAIL_DOMAIN_PART_MAX_LENGTH: 190,

  // VALUES UNIQUENESS
  EMAIL_ALREADY_EXISTS: 501,
  PASSWORD_ALREADY_EXISTS: 502,
  TEL_NUM_ALREADY_EXISTS: 503,

  // JWT SESSION
  SESSION_EXPIRED: 600,
  INVALID_REFRESH_SESSION: 601,
  TOKEN_NOT_PROVIDED: 602,
  REFRESH_TOKEN_NOT_PROVIDED: 603,

  EMAIL_OR_TEL_NUM_IS_REQUIRED: 900,
};